### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by rurban** [IBirdSoft/openfpm_pdata_1.1.0#1]
* Website doc bugs:
http://openfpm.mpi-cbg.de/openfpm_scripts:

./script/install_BOOST => ./script/install_BOOST.sh
./script/install_PETSC => ./script/install_PETSC.sh

http://openfpm.mpi-cbg.de/install_from_source#intro-wrapper
git clone https://github.com/IBirdSoft/openfpm_pdata_1.1.0.git && cd openfpm_pdata
=> cd openfpm_pdata_1.1.0

* automake warnings: missing foreign, missing -I m4. see PR #2 
```
Warning: Several files expected of projects that conform to the GNU
coding standards were not found.  The files were automatically added
for you since you do not have a 'foreign' declaration specified.

Considered adding 'foreign' to AM_INIT_AUTOMAKE in configure.ac
or to AUTOMAKE_OPTIONS in your top-level Makefile.am file.
```

* configure.ac syntax error: `if [x"have_quad_math" == x"yes" $&& x"have_quad_math" == x"yes" ]; then`
=> `if test x"$have_quad_math" = x"yes"; then`
see PR#2

same problem in openfpm_data_1.1.0 also. same patch.

**Comment by incardon** [comment]
Thank you very much, documentation fixed
