### ISSUE TITLE
Can you add write_time() for vector_dist

### ISSUE THREAD

**Issue by ZhouleiJoeStone** [IBirdSoft/openfpm_pdata_1.1.0#5]
I want to write results at time not in frame. 
According to the solution in this [webpage](http://www.visitusers.org/index.php?title=Time_and_Cycle_in_VTK_files)
I add 
"FIELD FieldData 1
TIME 1 1 double
1.23456789
"
in the vtk_header

So, I add write_time() function after the write_frame() in vector_dist.hpp and VTKWrite_point_set.hpp:

in [vector_dist.hpp](https://github.com/ZhouleiJoeStone/Pictures/blob/master/vector_dist.hpp) add:

         /*! \brief Output particle position and properties
	 *
	 * \param out output
	 * \param iteration (we can append the number at the end of the file_name)
	 * \param time (we can append the number at the end of the file_name)
	 * \param opt VTK_WRITER, CSV_WRITER, it is also possible to choose the format for  VTK
	 *            FORMAT_BINARY. (the default is ASCII format)
	 *
	 * \return if the file has been written correctly
	 *
	 */
	inline bool write_time(std::string out, size_t iteration, double time,int opt = VTK_WRITER)
	{
		if ((opt & 0x0FFF0000) == CSV_WRITER)
		{
			// CSVWriter test
			CSVWriter<openfpm::vector<Point<dim, St>>, openfpm::vector<prop> > csv_writer;

			std::string output = std::to_string(out + "_" + std::to_string(v_cl.getProcessUnitID()) + "_" + std::to_string(iteration) + std::to_string(".csv"));

			// Write the CSV
			return csv_writer.write(output, v_pos, v_prp);
		}
		else
		{
			file_type ft = file_type::ASCII;

			if (opt & FORMAT_BINARY)
				ft = file_type::BINARY;

			// VTKWriter for a set of points
			VTKWriter<boost::mpl::pair<openfpm::vector<Point<dim,St>>, openfpm::vector<prop>>, VECTOR_POINTS> vtk_writer;
			vtk_writer.add(v_pos,v_prp,g_m);

			std::string output = std::to_string(out + "_" + std::to_string(v_cl.getProcessUnitID()) + "_" + std::to_string(iteration) + std::to_string(".vtk"));

			// Write the VTK file
			return vtk_writer.write_time(output,prp_names,time,"particles",ft);
		}
	}

in [VTKWrite_point_set.hpp](https://github.com/ZhouleiJoeStone/Pictures/blob/master/VTKWriter_point_set.hpp) add:

	/*! \brief It write a VTK file from a vector of points
	 *
	 * \tparam prp_out which properties to output [default = -1 (all)]
	 *
	 * \param file path where to write
	 * \param f_name name of the dataset
	 * \param prop_names properties names
	 * \param ft specify if it is a VTK BINARY or ASCII file [default = ASCII]
	 *
	 * \return true if the write complete successfully
	 *
	 */
	template<int prp = -1> bool write_time(std::string file,
									  const openfpm::vector<std::string> & prop_names,
									  double time,
									  std::string f_name = "points" ,
									  file_type ft = file_type::ASCII
									  )
	{
		// Header for the vtk
		std::string vtk_header;
		// Point list of the VTK
		std::string point_list;
		// Vertex list of the VTK
		std::string vertex_list;
		// Graph header
		std::string vtk_binary_or_ascii;
		// vertex properties header
		std::string point_prop_header;
		// edge properties header
		std::string vertex_prop_header;
		// Data point header
		std::string point_data_header;
		// Data point
		std::string point_data;

		// VTK header
		vtk_header = "# vtk DataFile Version 3.0\n"
				     + f_name + "\n";

		// Choose if binary or ASCII
		if (ft == file_type::ASCII)
		{vtk_header += "ASCII\n";}
		else
		{vtk_header += "BINARY\n";}

		// Data type for graph is DATASET POLYDATA
		vtk_header += "DATASET POLYDATA\n";

          /************************************************************************************/
		//add by zhoulei
		//time information 
		vtk_header += "FIELD FieldData 1\n";
		vtk_header += "TIME 1 1 double\n";
		vtk_header += std::to_string(time)+"\n";
          /************************************************************************************/

		// point properties header
		point_prop_header = get_point_properties_list(ft);

		// Get point list
		point_list = get_point_list(ft);

		// vertex properties header
		vertex_prop_header = get_vertex_properties_list();

		// Get vertex list
		vertex_list = get_vertex_list(ft);

		// Get the point data header
		point_data_header = get_point_data_header();

		// For each property in the vertex type produce a point data

		prop_out_v< ele_vpp<typename pair::second>, typename pair::first::value_type::coord_type> pp(point_data, vpp, prop_names,ft);

		if (prp == -1)
			boost::mpl::for_each< boost::mpl::range_c<int,0, pair::second::value_type::max_prop> >(pp);
		else
			boost::mpl::for_each< boost::mpl::range_c<int,prp, prp> >(pp);

		// Add the last property
		pp.lastProp();

		// write the file
		std::ofstream ofs(file);

		// Check if the file is open
		if (ofs.is_open() == false)
		{std::cerr << "Error cannot create the VTK file: " + file + "\n";}

		ofs << vtk_header << point_prop_header << point_list <<
				vertex_prop_header << vertex_list << point_data_header << point_data;

		// Close the file

		ofs.close();

		// Completed succefully
		return true;
	}

};

In this way, I add a commom field data value "TIME" in the output file which will be displayed in the plot legends.

I think time is a important value in physics simulation.
In another way, I can give vector_dist a double property to record the time. But. it will waste lots of memory.
I look forward to a more elegant way to record the time.

**Comment by incardon** [comment]
It seems pretty good the solution you give, I will try to integrate in the next release thanks

**Comment by incardon** [comment]
The function write has now an additional parameter to insert meta-data. It is added in this way for future meta-data header addition. It is shown in the example 0_simple of version 2.0.0. Please feel free to reopen if you still find problems

**Comment by ZhouleiJoeStone** [comment]
Hello @incardon :
Thank you for adding meta-data in vtk file. 
When I use **meta_info** parameter in function
```
write_frame(std::string out, size_t iteration, std::string meta_info, int opt = VTK_WRITER)
```

In 8_DEM example, I write the result with time
```
...
if (cnt % 300 == 0)
{
	
//1.  add time meta-data in binary format file. Error happen.
parts.write_frame(output_dir+output_filename,cnt, std::string("time=")+std::to_string(timeSim.getwct()), VTK_WRITER | FORMAT_BINARY); //1 <--- Error,when add time in binary format.

//2. without time, just binary format. It's OK.	
//parts.write_frame(output_dir+output_filename,cnt, VTK_WRITER | FORMAT_BINARY);// 2 <---- without time, just binary format. It's OK

//3. add time in ASCII format, It's OK.
//parts.write_frame(output_dir+output_filename,cnt, std::string("time=")+std::to_string(timeSim.getwct()));// 3 <--- with time ,ASCII format, It's OK.

			
}
...
```

It's Ok when I write default ASCII file with time meta-data like 3 in the code.
But It's wrong when I use FORMAT_BINARY to add time meta-data like 1in the code, Paraview print the following [error](https://github.com/ZhouleiJoeStone/Pictures/blob/master/vtk_binary_error.png):
![error](https://github.com/ZhouleiJoeStone/Pictures/blob/master/vtk_binary_error.png)

[Here](https://github.com/ZhouleiJoeStone/Pictures/blob/master/code/main.cpp) is my test code link.

I think that the binary format may not accept the **meta-data**. But I don't know much about the VTK binary format.

**Comment by incardon** [comment]
After some test, It seems that there is a limit of 8 charachers in the time field

Adding in 

VTKWriter_point_set.hpp line 365

meta_string += std::to_string(time).substr(0,8);

to reduce the set of character solve the problem.

On the other hand it seems that this limit apply only to the binary format.

**Comment by incardon** [comment]
Should be fixed now.
