### ISSUE TITLE
boundary condition setting in examples/Grid/2_solve_equation

### ISSUE THREAD

**Issue by ZhouleiJoeStone** [IBirdSoft/openfpm_pdata_1.1.0#7]
Hello,
I think that the boundary condition should be set on the ghost layer in line 105,106 in [main.cpp](https://github.com/IBirdSoft/openfpm_pdata_1.1.0/blob/master/example/Grid/2_solve_eq/main.cpp).
So, it will be better to change the code from

	if (key_g.get(0) == 0 || key_g.get(0) == sz[0] ||
		key_g.get(1) == 0 || key_g.get(1) == sz[1])
	{
		// Boundary part
		g_dist.template get<0>(key) = 0.0;
	}

to

	if (key_g.get(0) < 0 ||   //<----------------- It should be less than 0
            key_g.get(0) == sz[0] ||
		key_g.get(1) < 0 || //<----------------- It should be less than 0
                  key_g.get(1) == sz[1])
	{
		// Boundary part
		g_dist.template get<0>(key) = 0.0;
	}

The boundary index should be less than 0 not equal to 0, because 0 is the first index in internal field not ghost layer.

**Comment by incardon** [comment]
Thanks.

I think the correction should be more like

if (key_g.get(0) == 0 || key_g.get(0) == sz[0] ||
	key_g.get(1) == 0 || key_g.get(1) == sz[1])
{
	// Boundary part
	g_dist.template get<0>(key) = 0.0;
}

**Comment by ZhouleiJoeStone** [comment]
I think I should explain more clearly.  The boundary value should be fixed in the calculation. If you set the 0 boundary condition in the internal field. The internal value will be changed in the following red_black step:

// 10000 iterations
    for (size_t i = 0 ; i < 10000 ; i++)
    {
        auto dom = g_dist.getDomainIterator();  //<------------the iterator will visit the boundary which you set    
        while (dom.isNext())
        {
            auto key = dom.get();
            auto key_g = g_dist.getGKey(key);
            if (red_black == false && (key_g.get(0) + key_g.get(1)) % 2 == 0)
            {++dom; continue;}
            else if (red_black == true && (key_g.get(0) + key_g.get(1)) % 2 == 1)
            {++dom; continue;}
            g_dist.get<0>(key) = (g_dist.get<0>(key.move(x,1)) + g_dist.template get<0>(key.move(x,-1)) +
                                 g_dist.get<0>(key.move(y,1)) + g_dist.template get<0>(key.move(y,-1)) +
                                 - 1.0)/4.0; // <--------the boundary condition set in internal field will be changed
            ++dom;
        }
        g_dist.template ghost_get<0>();
        red_black = !red_black;
    }

Actually, the 0 boundary value is not set by the "if" condition


if (key_g.get(0) == 0 || key_g.get(0) == sz[0]-1 ||
	key_g.get(1) == 0 || key_g.get(1) == sz[1]-1)
{
	// Boundary part
	g_dist.template get<0>(key) = 0.0;
}

but by the "else" condition		

                else
		{
			// Internal part  //<----------------- It include the ghost layer
			g_dist.template get<0>(key) = 0.0;
		}

because you will use "auto it = g_dist.getDomainGhostIterator();" , it will visit ghost layer in the "else" condition.

in your 5 point case,
 -1        0          1          2          3          4         5

#...........*---------*---------*---------*---------*..........#.

If you want to use the "if condition" to set the boundary value, the boundary value should be set in # .

I hope that my poor English helped to clarify the problem.

**Comment by incardon** [comment]
I see thanks

**Comment by incardon** [comment]
It should be fixed in the next version. Please feel free to reopen if you find more problems
